Repository BBarisKilic/Numbers, pull requests merged in 2023-10, with the labels that each got.

#9 refactor: apply linter rules
  .github/workflows/main.yaml
  analysis_options.yaml
  lib/src/app/app.dart
  lib/src/app/cubit/app_cubit.dart
  lib/src/config/routes/app_route.dart
  lib/src/config/themes/concretes/dark_app_theme_impl.dart
  lib/src/config/themes/concretes/light_app_theme_impl.dart
  lib/src/core/resources/abstracts/data_state.dart
  lib/src/core/resources/concretes/data_failure.dart
  lib/src/core/resources/concretes/data_success.dart
  lib/src/core/usecases/usecase.dart
  lib/src/core/utils/constants/sizes.dart
  lib/src/data/datasources/local/shared_pref_service/abstracts/shared_pref_service.dart
  lib/src/data/datasources/local/shared_pref_service/concretes/shared_pref_service_impl.dart
  lib/src/data/datasources/remote/numbers_service/abstracts/numbers_api_service.dart
  lib/src/data/datasources/remote/numbers_service/concretes/numbers_api_service_impl.dart
  lib/src/data/models/number_model.dart
  lib/src/data/repositories/number_repository_impl.dart
  lib/src/data/repositories/shared_pref_repository_impl.dart
  lib/src/domain/repositories/number_repository.dart
  lib/src/domain/repositories/shared_pref_repository.dart
  lib/src/domain/usecases/get_number_usecase.dart
  lib/src/domain/usecases/get_random_number_usecase.dart
  lib/src/domain/usecases/get_string_usecase.dart
  lib/src/domain/usecases/set_string_usecase.dart
  lib/src/injector.dart
  lib/src/presentation/number/cubit/number_cubit.dart
  lib/src/presentation/number/pages/number_page.dart
  lib/src/presentation/number/widgets/info_container.dart
  lib/src/presentation/number/widgets/number_text_form_field.dart
  lib/src/presentation/number/widgets/numpad_action_button.dart
  lib/src/presentation/number/widgets/numpad_grid_view.dart
  lib/src/presentation/number/widgets/numpad_number_button.dart
  lib/src/presentation/settings/cubit/settings_cubit.dart
  lib/src/presentation/settings/pages/settings_page.dart
  lib/src/presentation/settings/settings.dart
  lib/src/presentation/settings/widgets/copyright_text.dart
  lib/src/presentation/settings/widgets/options_list_view.dart
  lib/src/presentation/settings/widgets/themes_bottom_sheet.dart
  packages/custom_app_bar/analysis_options.yaml
  packages/sharp_toggle_switch/analysis_options.yaml
  packages/sharp_toggle_switch/lib/sharp_toggle_switch.dart
  test/src/data/repositories/number_repository_impl_test.dart
  test/src/domain/usecases/get_number_usecase_test.dart
  test/src/domain/usecases/get_random_number_usecase_test.dart
Labels: chore

#16 refactor: implement flutter_gen package #15
  analysis_options.yaml
  l10n.yaml
  lib/l10n/app_localizations.dart
  lib/l10n/app_localizations_en.dart
  lib/l10n/app_localizations_es.dart
  lib/l10n/l10n.dart
  lib/src/config/themes/dark_app_theme.dart
  lib/src/config/themes/light_app_theme.dart
  lib/src/core/constants/assets.gen.dart
  lib/src/core/constants/constants.dart
  lib/src/core/constants/fonts.gen.dart
  lib/src/core/constants/icons.dart
  lib/src/features/number/presentation/pages/number_page.dart
  lib/src/features/settings/presentation/cubit/settings_cubit.dart
  lib/src/features/settings/presentation/pages/settings_page.dart
  lib/src/features/settings/presentation/widgets/themes_bottom_sheet.dart
  pubspec.lock
  pubspec.yaml
Labels: refactor

#18 feat: add localization support
  l10n.yaml
  lib/l10n/app_localizations_en.dart
  lib/l10n/app_localizations_es.dart
  lib/l10n/arb/app_en.arb
  lib/l10n/arb/app_es.arb
  lib/l10n/l10n.dart
  lib/src/app/presentation/widgets/app.dart
  lib/src/core/constants/constants.dart
  lib/src/core/constants/texts.dart
  lib/src/core/core.dart
  lib/src/core/extensions/build_context_ext.dart
  lib/src/core/l10n/app_localizations.dart
  lib/src/core/l10n/app_localizations_en.dart
  lib/src/core/l10n/arb/app_en.arb
  lib/src/core/l10n/l10n.dart
  lib/src/features/number/data/models/number_dto.dart
  lib/src/features/number/domain/entities/number.dart
  lib/src/features/number/presentation/pages/number_page.dart
  lib/src/features/number/presentation/widgets/info_container.dart
  lib/src/features/number/presentation/widgets/numpad_grid_view.dart
  lib/src/features/settings/presentation/cubit/settings_cubit.dart
  lib/src/features/settings/presentation/pages/settings_page.dart
  lib/src/features/settings/presentation/widgets/copyright_text.dart
  lib/src/features/settings/presentation/widgets/themes_bottom_sheet.dart
  test/helpers/pump_app.dart
Labels: enhancement
